export type { CodeEditorFeatures } from './types'
export { FeatureProvider, useFeatures } from './feature-context'
export { useEditorStore } from './store/editor-store'
export { useUiStore } from './store/ui-store'
export { useResizable } from './useResizable'
export { useShallow } from 'zustand/react/shallow'
export { Loading } from './components/Loading'
export type { ContentRepository, FileContent } from './content/localForageContentRepository'
export { createLocalForageContentRepository } from './content/localForageContentRepository'
export { openFile, closeFile, setFileContent, addFile, deleteFile, renameFile } from './content/editorService'
export * from './utils/buffer'
